openapi: '3.0.3'
info:
  title: ISAGI NEWS API
  version: '1.0'
servers:
  - url: http://localhost:3000/
paths:
  /auth/register:
    post:
      tags:
        - auth
      requestBody: 
        content: 
          application/x-www-form-urlencoded: 
            schema: 
              $ref: '#/components/schemas/NewUserRequest'
        required: true
      responses:
        '200':
          description: Usuario registrado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Datos no validos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '422': 
          description: Usuario ya registrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /auth/login:
    post:
      tags:
        - auth
      requestBody: 
        content: 
          application/x-www-form-urlencoded: 
            schema: 
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: Usuario logueado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Credenciales no validas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
components:
  schemas:
    MessageResponse:
      type: object
      properties:
        status:
          type: integer
          description: Codigo de estado de la respuesta
        message:
          type: string
          description: Mensaje de respuesta
    NewUserRequest: 
      type: object
      properties: 
        email: 
          type: string
          description: Email del usuario
        password: 
          type: string
          description: Contraseña del usuario
      required:
        - email
        - password
    LoginRequest: 
      type: object
      properties: 
        email: 
          type: string
          description: Email del usuario
        password: 
          type: string
          description: Contraseña del usuario
        remember: 
          type: boolean
          description: Recordar usuario
      required:
        - email
        - password
        - remember
    LoginResponse:
      type: object
      properties:
        status: 
          type: integer
          description: Codigo de estado de la respuesta
        token:
          type: string
          description: Token de autenticacion
